import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'People Discovery',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='bg-bjssOne flex justify-between h-20 p-4'>
          <Link
            rel='preload'
            href={'/'}
            className='font-bold text-white text-3xl '
          >
            People Discovery
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
